export const Type = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCT_DETAIL: "SET_PRODUCT_DETAIL",
  SET_USER: "SET_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SAVE_FOR_LATER: "SAVE_FOR_LATER", // newly added
  EMPTY_CART: "EMPTY_CART", // newly added
};
